### ISSUE TITLE
Control step from prop passed to StepWizard

### ISSUE THREAD

**Issue by LukasDeco** [jcmcneal/react-step-wizard#25] opened 2019-04-12 12:40 UTC
This is more of a question than an issue. I wanted to use the initialStep prop to change the step, BUT I needed to do this after the component had already mounted. At least I think I need to do it this way.

Is there a way to control the step of the wizard from a prop even after it mounts? I appreciate any help. Thanks!

Here is my StepWizard:
''`<StepWizard isLazyMount={true} initialStep={props.initialStep} ref={el => this.stepWizard = el}>
        ...some steps
      </StepWizard>`''

I change the initialStep prop on a setState in my app based on a button click.

Thanks!

**Comment by jcmcneal** [comment] 2019-04-18 05:18
Hey, thanks for your input. This is more or less a duplicate issue. Considering the popular request of this feature I will try and get this out soon.

Duplicate of #23

**Closed** 2019-04-25 16:23 UTC
