### ISSUE TITLE
Container height problem

### ISSUE THREAD

**Issue by thebarty** [jcmcneal/react-step-wizard#44] opened 2019-10-18 12:46 UTC
Hi guys,

I have a problem with the container-height, where I am basically experiencing this issue here and get white-space under the footer (https://stackoverflow.com/questions/34188161/remove-white-space-below-footer)

When i enable `isLazyMount` the first step looks good, but after going to the next step the white-space appears.

Has anyone got the same problem and knows a solution?

**Comment by Eencsio** [comment] 2019-11-20 02:46
I have the same problem, but I don't have a solution

**Comment by thebarty** [comment] 2019-11-21 22:32
I did NOT solve it but kind of made it less obvious by:

 1) using css `height: 100he` on the wrapping container
 2) switching animations to a different style

I basically still have the issue but the user only sees it when scrolling down

**Comment by segicm** [comment] 2020-02-18 14:46
I had this problem, where the components with the larger height made the white space to the smaller components. The solution that worked for me was to set the non-active components to **_display: none;_** so the white space will not be shown. Here's how:
`.rsw_2f{
  display: none;
}
.rsw_3G{
  display: block;
}`

All step components will have the **.rsw_2f** class and only the active one will have the **.rsw_3G** class.

**Comment by eatoncw** [comment] 2020-04-25 20:12
Ok, following on from @segicm - I was able to avoid this same container height (which resulted in long scrolling, white space) by add a min-height to `.rsw_3g` - eg:

```
.rsw_2f {
  display: none;
}
.rsw_3G {
  display: block;
  min-height: 100vh;
}
```

I had this issue with and without lazy loading, but this fixed it.

**Comment by halabe15** [comment] 2020-05-18 07:23
Activating isLazyMount worked for me!!

**Comment by resolritter** [comment] 2020-11-14 02:46
It doesn't seem to me that this would be a concern for this library specifically. Not without a reproducible demo, anyway.

Closing due to unactionability.

**Closed by resolritter** 2020-11-14 02:46 UTC
Labels: question

**Comment by Bogdastotel** [comment] 2021-04-14 13:37
> I had this problem, where the components with the larger height made the white space to the smaller components. The solution that worked for me was to set the non-active components to **_display: none;_** so the white space will not be shown. Here's how:
> `.rsw_2f{ display: none; } .rsw_3G{ display: block; }`
> 
> All step components will have the **.rsw_2f** class and only the active one will have the **.rsw_3G** class.
Thanks for the  help!

**Comment by Bogdastotel** [comment] 2021-04-14 13:37
> I had this problem, where the components with the larger height made the white space to the smaller components. The solution that worked for me was to set the non-active components to **_display: none;_** so the white space will not be shown. Here's how:
> `.rsw_2f{ display: none; } .rsw_3G{ display: block; }`
> 
> All step components will have the **.rsw_2f** class and only the active one will have the **.rsw_3G** class.

@segicm  thanks for the help! :)

**Comment by sasha-larson** [comment] 2023-02-13 18:15
I also had this issue but was utilizing a form across the steps. I found that utilizing the isActive prop from step-wizard and hiding the step component when it's not active solved the issue

**Comment by jcarteaga1** [comment] 2023-03-28 22:38
> También tuve este problema, pero estaba usando un formulario en los pasos. Descubrí que utilizar el accesorio isActive del asistente de pasos y ocultar el componente de paso cuando no está activo resolvió el problema

Hello, can you show an example of how you solved it? i have the same error but nothing works for me
